### ISSUE TITLE
Eliminate username leaking from FIDO logins

### ISSUE THREAD

**Issue by zbreit** [team-pass/FIDO-login#60]
Currently, the FIDO `/login` route will reveal whether or not a username exists by aborting early. To prevent this, maybe we can go along w/ the FIDO authentication process regardless of whether the email is correct. Might also apply for the `/register` route as well.

**Comment by jckong99** [comment]
As you say, this problem applies to both FIDO login and account registration in general, so we'd have to fix both for it to matter. The FIDO login leak can probably be addressed in the way you suggest, but registration is tougher.

The only way I can think of to eliminate username leaks when registering is to do the thing where you send an email to a new user to verify their account. This covers several cases: if it's an email address already in use, the original account owner can just ignore the email; if it's a nonexistent address, nothing effectively happens; otherwise, the newly registered can go to their email, verify, and proceed to their new profile.

Do we want to actually go through and commit to this email process?

**Comment by zbreit** [comment]
For now, let's just do login leaking. The way registration leaks are typically prevented are captchas (to prevent brute force attacks). However, there are very few good captcha services that don't require separate accounts (eg google recaptcha).

**Comment by zbreit** [comment]
We can leave the registration email feature in the future.
