### ISSUE TITLE
Add Metric for # of failed login attempts using each login method

### ISSUE THREAD

**Issue by zbreit** [team-pass/FIDO-login#71]
In many usability studies, they collected data on the number of successful login attempts using passwords vs. FIDO. This would be a useful piece of data to know, and we should add it to our system.

**Comment by bkodali12** [comment]
There seems to be an issue with accurately getting the number of failed login attempts for webauthn. Specifically, when Jim and I tried to get a failed login attempt using my computer's fingerprint scanner, we found that there wasn't a way for our web app to get that information. Since Windows Hello was handling the biometrics authentication, it was the service that knew whether a user provided the right fingerprint or not. If my fingerprint did not match, then all it did was ask me to try again. Eventually, there was a timeout where our web app received this message: "Error when creating credential: DOMException: The operation either timed out or was not allowed". We could technically use this error to count failed login attempts but it would also include cases where a user gets distracted and does not finish signing in.
